//
//  ActivateEnum.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_ACTIVATEENUM
#define APIMATIC_ACTIVATEENUM
typedef NS_ENUM(NSInteger, ActivateEnum)
{
        ActivateMActivate = 1, //TODO: Write general description for this method
        ActivateDeActivate = 0, //TODO: Write general description for this method
};

#endif