//
//  AudioUrlEnum.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_AUDIOURLENUM
#define APIMATIC_AUDIOURLENUM
 
enum AudioUrlEnum
{
        AudioUrlMp3, //mp3 file
        AudioUrlWav, //wav file
};

#endif