//
//  CreateCallsRecordcallsInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateCallsRecordcallsInput.h"

@implementation CreateCallsRecordcallsInput

/**
* The unique identifier of each call resource
*/
@synthesize callSid;

/**
* Set true to initiate recording or false to terminate recording
*/
@synthesize record;

/**
* The leg of the call to record
*/
@synthesize direction;

/**
* Time in seconds the recording duration should not exceed
*/
@synthesize timeLimit;

/**
* URL consulted after the recording completes
*/
@synthesize callBackUrl;

/**
* Format of the recording file. Can be .mp3 or .wav
*/
@synthesize fileformat;

 /**
 * For serialization of enum DirectionEnum type property as NSString*
 */
-(id) JSONObjectForDirection
{
     
    return [DirectionEnumHelper stringFromDirectionEnum:(enum DirectionEnum) direction withDefault: nil];

}

/**
 * For deserialization of enum DirectionEnum type property from NSString*
 */
 
-(void)setDirectionWithNSString:(NSString*) strValue
{
    direction = [DirectionEnumHelper directionEnumFromString:(NSString*) strValue];
}


 /**
 * For serialization of enum FileformatEnum type property as NSString*
 */
-(id) JSONObjectForFileformat
{
     
    return [FileformatEnumHelper stringFromFileformatEnum:(enum FileformatEnum) fileformat withDefault: nil];

}

/**
 * For deserialization of enum FileformatEnum type property from NSString*
 */
 
-(void)setFileformatWithNSString:(NSString*) strValue
{
    fileformat = [FileformatEnumHelper fileformatEnumFromString:(NSString*) strValue];
}


@end