//
//  CreateIncomingphoneReleasenumberByResponseTypePostInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateIncomingphoneReleasenumberByResponseTypePostInput.h"

@implementation CreateIncomingphoneReleasenumberByResponseTypePostInput

/**
* A valid 10-digit Ytel number (E.164 format).
*/
@synthesize phoneNumber;

/**
* Response type format xml or json
*/
@synthesize responseType;

@end