//
//  CreateCarrierLookuplistInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateCarrierLookuplistInput.h"

@implementation CreateCarrierLookuplistInput

/**
* The page count to retrieve from the total results in the collection. Page indexing starts at 1.
*/
@synthesize page;

/**
* The count of objects to return per page.
*/
@synthesize pageSize;

-(id)init
{
    if (self = [super init])
    {
        self.page = 1;
        self.pageSize = 10;
    }
    return self;
}

@end