//
//  CreateSmsListsmsInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CREATESMSLISTSMSINPUT
#define APIMATIC_CREATESMSLISTSMSINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol CreateSmsListsmsInput
@end

@interface CreateSmsListsmsInput : NSObject

/**
* The page count to retrieve from the total results in the collection. Page indexing starts at 1.
*/
@property int page;

/**
* Number of individual resources listed in the response per page
*/
@property int pageSize;

/**
* Filter SMS message objects from this valid 10-digit phone number (E.164 format).
*/
@property NSString* from;

/**
* Filter SMS message objects to this valid 10-digit phone number (E.164 format).
*/
@property NSString* to;

/**
* Only list SMS messages sent in the specified date range
*/
@property NSString* dateSent;

@end
#endif