//
//  CreateUsageListusageInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CREATEUSAGELISTUSAGEINPUT
#define APIMATIC_CREATEUSAGELISTUSAGEINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "ProductCode27Enum.h"
#import "ProductCode27EnumHelper.h"


//protocol defined for deserialization of JSON
@protocol CreateUsageListusageInput
@end

@interface CreateUsageListusageInput : NSObject

/**
* Filter usage results by product type.
*/
@property enum ProductCode27Enum productCode;

/**
* Filter usage objects by start date.
*/
@property NSString* startDate;

/**
* Filter usage objects by end date.
*/
@property NSString* endDate;

/**
* Will include all subaccount usage data
*/
@property NSString* includeSubAccounts;

@end
#endif