//
//  CreateCallsGroupcallInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateCallsGroupcallInput.h"

@implementation CreateCallsGroupcallInput

/**
* This number to display on Caller ID as calling
*/
@synthesize from;

/**
* Please enter multiple E164 number. You can add max 10 numbers. Add numbers separated with comma. e.g : 1111111111,2222222222
*/
@synthesize to;

/**
* URL requested once the call connects
*/
@synthesize url;

/**
* Define the DTMF that the called party should send to bridge the call. Allowed Values : 0-9, #, *
*/
@synthesize groupConfirmKey;

/**
* Specify the audio file you want to play when the called party picks up the call
*/
@synthesize groupConfirmFile;

/**
* Specifies the HTTP method used to request the required URL once call connects.
*/
@synthesize method;

/**
* URL that can be requested to receive notification when call has ended. A set of default parameters will be sent here once the call is finished.
*/
@synthesize statusCallBackUrl;

/**
* Specifies the HTTP methodlinkclass used to request StatusCallbackUrl.
*/
@synthesize statusCallBackMethod;

/**
* URL requested if the initial Url parameter fails or encounters an error
*/
@synthesize fallBackUrl;

/**
* Specifies the HTTP method used to request the required FallbackUrl once call connects.
*/
@synthesize fallBackMethod;

/**
* URL that can be requested every 60 seconds during the call to notify of elapsed time and pass other general information.
*/
@synthesize heartBeatUrl;

/**
* Specifies the HTTP method used to request HeartbeatUrl.
*/
@synthesize heartBeatMethod;

/**
* Time (in seconds) we should wait while the call is ringing before canceling the call
*/
@synthesize timeout;

/**
* DTMF Digits to play to the call once it connects. 0-9, #, or *
*/
@synthesize playDtmf;

/**
* Specifies if the caller id will be hidden
*/
@synthesize hideCallerId;

/**
* Specifies if the call should be recorded
*/
@synthesize record;

/**
* Recording parameters will be sent here upon completion
*/
@synthesize recordCallBackUrl;

/**
* Method used to request the RecordCallback URL.
*/
@synthesize recordCallBackMethod;

/**
* Specifies if the call recording should be transcribed
*/
@synthesize transcribe;

/**
* Transcription parameters will be sent here upon completion
*/
@synthesize transcribeCallBackUrl;

 /**
 * For serialization of enum GroupConfirmFileEnum type property as NSString*
 */
-(id) JSONObjectForGroupConfirmFile
{
     
    return [GroupConfirmFileEnumHelper stringFromGroupConfirmFileEnum:(enum GroupConfirmFileEnum) groupConfirmFile withDefault: nil];

}

/**
 * For deserialization of enum GroupConfirmFileEnum type property from NSString*
 */
 
-(void)setGroupConfirmFileWithNSString:(NSString*) strValue
{
    groupConfirmFile = [GroupConfirmFileEnumHelper groupConfirmFileEnumFromString:(NSString*) strValue];
}


@end