//
//  CreateRecordingListrecordingInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CREATERECORDINGLISTRECORDINGINPUT
#define APIMATIC_CREATERECORDINGLISTRECORDINGINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol CreateRecordingListrecordingInput
@end

@interface CreateRecordingListrecordingInput : NSObject

/**
* The page count to retrieve from the total results in the collection. Page indexing starts at 1.
*/
@property int page;

/**
* The count of objects to return per page.
*/
@property int pagesize;

/**
* Filter results by creation date
*/
@property NSString* datecreated;

/**
* The unique identifier for a call.
*/
@property NSString* callsid;

@end
#endif