//
//  CreateShortcodeListshortcodeInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CREATESHORTCODELISTSHORTCODEINPUT
#define APIMATIC_CREATESHORTCODELISTSHORTCODEINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol CreateShortcodeListshortcodeInput
@end

@interface CreateShortcodeListshortcodeInput : NSObject

/**
* The page count to retrieve from the total results in the collection. Page indexing starts at 1.
*/
@property int page;

/**
* Number of individual resources listed in the response per page
*/
@property int pagesize;

/**
* Only list keywords of shortcode
*/
@property NSString* shortcode;

@end
#endif