//
//  CreateTranscriptionsListtranscriptionInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CREATETRANSCRIPTIONSLISTTRANSCRIPTIONINPUT
#define APIMATIC_CREATETRANSCRIPTIONSLISTTRANSCRIPTIONINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "StatusEnum.h"
#import "StatusEnumHelper.h"


//protocol defined for deserialization of JSON
@protocol CreateTranscriptionsListtranscriptionInput
@end

@interface CreateTranscriptionsListtranscriptionInput : NSObject

/**
* The page count to retrieve from the total results in the collection. Page indexing starts at 1.
*/
@property int page;

/**
* The count of objects to return per page.
*/
@property int pagesize;

/**
* The state of the transcription.
*/
@property enum StatusEnum status;

/**
* The date the transcription took place.
*/
@property NSString* dateTranscribed;

@end
#endif