//
//  CreateShortcodeGetinboundsmsInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateShortcodeGetinboundsmsInput.h"

@implementation CreateShortcodeGetinboundsmsInput

/**
* The page count to retrieve from the total results in the collection. Page indexing starts at 1.
*/
@synthesize page;

/**
* Number of individual resources listed in the response per page
*/
@synthesize pagesize;

/**
* From Number to Inbound ShortCode
*/
@synthesize from;

/**
* Only list messages sent to this Short Code
*/
@synthesize shortcode;

/**
* Only list messages sent with the specified date
*/
@synthesize datecreated;

-(id)init
{
    if (self = [super init])
    {
        self.page = 1;
        self.pagesize = 10;
    }
    return self;
}

@end