//
//  CreateConferencesViewParticipantInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateConferencesViewParticipantInput.h"

@implementation CreateConferencesViewParticipantInput

/**
* The unique identifier for a conference object.
*/
@synthesize conferenceSid;

/**
* The unique identifier for a participant object.
*/
@synthesize participantSid;

@end