//
//  CreateCallsInterruptcallsInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateCallsInterruptcallsInput.h"

@implementation CreateCallsInterruptcallsInput

/**
* The unique identifier for voice call that is in progress.
*/
@synthesize callSid;

/**
* URL the in-progress call will be redirected to
*/
@synthesize url;

/**
* The method used to request the above Url parameter
*/
@synthesize method;

/**
* Status to set the in-progress call to
*/
@synthesize status;

 /**
 * For serialization of enum Status24Enum type property as NSString*
 */
-(id) JSONObjectForStatus
{
     
    return [Status24EnumHelper stringFromStatus24Enum:(enum Status24Enum) status withDefault: nil];

}

/**
 * For deserialization of enum Status24Enum type property from NSString*
 */
 
-(void)setStatusWithNSString:(NSString*) strValue
{
    status = [Status24EnumHelper status24EnumFromString:(NSString*) strValue];
}


@end