//
//  CreateConferencesViewParticipantInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CREATECONFERENCESVIEWPARTICIPANTINPUT
#define APIMATIC_CREATECONFERENCESVIEWPARTICIPANTINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol CreateConferencesViewParticipantInput
@end

@interface CreateConferencesViewParticipantInput : NSObject

/**
* The unique identifier for a conference object.
*/
@property NSString* conferenceSid;

/**
* The unique identifier for a participant object.
*/
@property NSString* participantSid;

@end
#endif