//
//  CreateShortcodeGetinboundsmsInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CREATESHORTCODEGETINBOUNDSMSINPUT
#define APIMATIC_CREATESHORTCODEGETINBOUNDSMSINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol CreateShortcodeGetinboundsmsInput
@end

@interface CreateShortcodeGetinboundsmsInput : NSObject

/**
* The page count to retrieve from the total results in the collection. Page indexing starts at 1.
*/
@property int page;

/**
* Number of individual resources listed in the response per page
*/
@property int pagesize;

/**
* From Number to Inbound ShortCode
*/
@property NSString* from;

/**
* Only list messages sent to this Short Code
*/
@property NSString* shortcode;

/**
* Only list messages sent with the specified date
*/
@property NSString* datecreated;

@end
#endif