//
//  CreateConferencesListconferenceInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CREATECONFERENCESLISTCONFERENCEINPUT
#define APIMATIC_CREATECONFERENCESLISTCONFERENCEINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol CreateConferencesListconferenceInput
@end

@interface CreateConferencesListconferenceInput : NSObject

/**
* The page count to retrieve from the total results in the collection. Page indexing starts at 1.
*/
@property int page;

/**
* Number of individual resources listed in the response per page
*/
@property int pagesize;

/**
* Only return conferences with the specified FriendlyName
*/
@property NSString* friendlyName;

/**
* Conference created date
*/
@property NSString* dateCreated;

@end
#endif