//
//  CreateIncomingphoneUpdatenumberInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CREATEINCOMINGPHONEUPDATENUMBERINPUT
#define APIMATIC_CREATEINCOMINGPHONEUPDATENUMBERINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol CreateIncomingphoneUpdatenumberInput
@end

@interface CreateIncomingphoneUpdatenumberInput : NSObject

/**
* A valid Ytel number (E.164 format).
*/
@property NSString* phoneNumber;

/**
* URL requested once the call connects
*/
@property NSString* voiceUrl;

/**
* Phone number friendly name description
*/
@property NSString* friendlyName;

/**
* Post or Get
*/
@property NSString* voiceMethod;

/**
* URL requested if the voice URL is not available
*/
@property NSString* voiceFallbackUrl;

/**
* Post or Get
*/
@property NSString* voiceFallbackMethod;

/**
* callback url after a hangup occurs
*/
@property NSString* hangupCallback;

/**
* Post or Get
*/
@property NSString* hangupCallbackMethod;

/**
* URL requested once the call connects
*/
@property NSString* heartbeatUrl;

/**
* URL that can be requested every 60 seconds during the call to notify of elapsed time
*/
@property NSString* heartbeatMethod;

/**
* URL requested when an SMS is received
*/
@property NSString* smsUrl;

/**
* Post or Get
*/
@property NSString* smsMethod;

/**
* URL used if any errors occur during execution of InboundXML from an SMS or at initial request of the SmsUrl.
*/
@property NSString* smsFallbackUrl;

/**
* The HTTP method Ytel will use when URL requested if the SmsUrl is not available.
*/
@property NSString* smsFallbackMethod;

@end
#endif