//
//  CreateUsageListusageInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateUsageListusageInput.h"

@implementation CreateUsageListusageInput

/**
* Filter usage results by product type.
*/
@synthesize productCode;

/**
* Filter usage objects by start date.
*/
@synthesize startDate;

/**
* Filter usage objects by end date.
*/
@synthesize endDate;

/**
* Will include all subaccount usage data
*/
@synthesize includeSubAccounts;

-(id)init
{
    if (self = [super init])
    {
        self.productCode = [ProductCode27EnumHelper productCode27EnumFromString:@"0"];
        self.startDate = @"2016-09-06";
        self.endDate = @"2016-09-06";
    }
    return self;
}

@end