//
//  CreateEmailListblockemailInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateEmailListblockemailInput.h"

@implementation CreateEmailListblockemailInput

/**
* The starting point of the list of blocked emails that should be returned.
*/
@synthesize offset;

/**
* The count of results that should be returned.
*/
@synthesize limit;

@end