//
//  CreateIncomingphoneReleasenumberByResponseTypePostInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CREATEINCOMINGPHONERELEASENUMBERBYRESPONSETYPEPOSTINPUT
#define APIMATIC_CREATEINCOMINGPHONERELEASENUMBERBYRESPONSETYPEPOSTINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol CreateIncomingphoneReleasenumberByResponseTypePostInput
@end

@interface CreateIncomingphoneReleasenumberByResponseTypePostInput : NSObject

/**
* A valid 10-digit Ytel number (E.164 format).
*/
@property NSString* phoneNumber;

/**
* Response type format xml or json
*/
@property NSString* responseType;

@end
#endif