//
//  CreateEmailSendemailsInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateEmailSendemailsInput.h"

@implementation CreateEmailSendemailsInput

/**
* A valid address that will receive the email. Multiple addresses can be separated by using commas.
*/
@synthesize to;

/**
* Specifies the type of email to be sent
*/
@synthesize type;

/**
* The subject of the mail. Must be a valid string.
*/
@synthesize subject;

/**
* The email message that is to be sent in the text.
*/
@synthesize message;

/**
* A valid address that will send the email.
*/
@synthesize from;

/**
* Carbon copy. A valid address that will receive the email. Multiple addresses can be separated by using commas.
*/
@synthesize cc;

/**
* Blind carbon copy. A valid address that will receive the email. Multiple addresses can be separated by using commas.
*/
@synthesize bcc;

/**
* A file that is attached to the email. Must be less than 7 MB in size.
*/
@synthesize attachment;

 /**
 * For serialization of enum TypeEnum type property as NSString*
 */
-(id) JSONObjectForType
{
     
    return [TypeEnumHelper stringFromTypeEnum:(enum TypeEnum) type withDefault: nil];

}

/**
 * For deserialization of enum TypeEnum type property from NSString*
 */
 
-(void)setTypeWithNSString:(NSString*) strValue
{
    type = [TypeEnumHelper typeEnumFromString:(NSString*) strValue];
}


@end