//
//  CreateCallsMakecallInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateCallsMakecallInput.h"

@implementation CreateCallsMakecallInput

/**
* A valid Ytel Voice enabled number (E.164 format) that will be initiating the phone call.
*/
@synthesize from;

/**
* To number
*/
@synthesize to;

/**
* URL requested once the call connects
*/
@synthesize url;

/**
* Specifies the HTTP method used to request the required URL once call connects.
*/
@synthesize method;

/**
* URL that can be requested to receive notification when call has ended. A set of default parameters will be sent here once the call is finished.
*/
@synthesize statusCallBackUrl;

/**
* Specifies the HTTP methodlinkclass used to request StatusCallbackUrl.
*/
@synthesize statusCallBackMethod;

/**
* URL requested if the initial Url parameter fails or encounters an error
*/
@synthesize fallBackUrl;

/**
* Specifies the HTTP method used to request the required FallbackUrl once call connects.
*/
@synthesize fallBackMethod;

/**
* URL that can be requested every 60 seconds during the call to notify of elapsed tim
*/
@synthesize heartBeatUrl;

/**
* Specifies the HTTP method used to request HeartbeatUrl.
*/
@synthesize heartBeatMethod;

/**
* Time (in seconds) Ytel should wait while the call is ringing before canceling the call
*/
@synthesize timeout;

/**
* DTMF Digits to play to the call once it connects. 0-9, #, or *
*/
@synthesize playDtmf;

/**
* Specifies if the caller id will be hidden
*/
@synthesize hideCallerId;

/**
* Specifies if the call should be recorded
*/
@synthesize record;

/**
* Recording parameters will be sent here upon completion
*/
@synthesize recordCallBackUrl;

/**
* Method used to request the RecordCallback URL.
*/
@synthesize recordCallBackMethod;

/**
* Specifies if the call recording should be transcribed
*/
@synthesize transcribe;

/**
* Transcription parameters will be sent here upon completion
*/
@synthesize transcribeCallBackUrl;

/**
* How Ytel should handle the receiving numbers voicemail machine
*/
@synthesize ifMachine;

/**
* URL requested when IfMachine=continue
*/
@synthesize ifMachineUrl;

/**
* Method used to request the IfMachineUrl.
*/
@synthesize ifMachineMethod;

/**
* Specify if survey should be enable or not
*/
@synthesize feedback;

/**
* The unique identifier for the survey.
*/
@synthesize surveyId;

 /**
 * For serialization of enum IfMachineEnum type property as NSString*
 */
-(id) JSONObjectForIfMachine
{
     
    return [IfMachineEnumHelper stringFromIfMachineEnum:(enum IfMachineEnum) ifMachine withDefault: nil];

}

/**
 * For deserialization of enum IfMachineEnum type property from NSString*
 */
 
-(void)setIfMachineWithNSString:(NSString*) strValue
{
    ifMachine = [IfMachineEnumHelper ifMachineEnumFromString:(NSString*) strValue];
}


@end