//
//  CreateCarrierLookuplistInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CREATECARRIERLOOKUPLISTINPUT
#define APIMATIC_CREATECARRIERLOOKUPLISTINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol CreateCarrierLookuplistInput
@end

@interface CreateCarrierLookuplistInput : NSObject

/**
* The page count to retrieve from the total results in the collection. Page indexing starts at 1.
*/
@property int page;

/**
* The count of objects to return per page.
*/
@property int pageSize;

@end
#endif