//
//  CreateLetterListsletterInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateLetterListsletterInput.h"

@implementation CreateLetterListsletterInput

/**
* The page count to retrieve from the total results in the collection. Page indexing starts at 1.
*/
@synthesize page;

/**
* The count of objects to return per page.
*/
@synthesize pagesize;

/**
* The unique identifier for a letter object.
*/
@synthesize lettersid;

/**
* The date the letter was created.
*/
@synthesize dateCreated;

-(id)init
{
    if (self = [super init])
    {
        self.page = 1;
        self.pagesize = 10;
    }
    return self;
}

@end