//
//  CreateShortcodeUpdateshortcodeInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateShortcodeUpdateshortcodeInput.h"

@implementation CreateShortcodeUpdateshortcodeInput

/**
* List of valid shortcode to your Ytel account
*/
@synthesize shortcode;

/**
* User generated name of the shortcode
*/
@synthesize friendlyName;

/**
* URL that can be requested to receive notification when call has ended. A set of default parameters will be sent here once the call is finished.
*/
@synthesize callbackUrl;

/**
* Specifies the HTTP method used to request the required StatusCallBackUrl once call connects.
*/
@synthesize callbackMethod;

/**
* URL used if any errors occur during execution of InboundXML or at initial request of the required Url provided with the POST.
*/
@synthesize fallbackUrl;

/**
* Specifies the HTTP method used to request the required FallbackUrl once call connects.
*/
@synthesize fallbackUrlMethod;

@end