//
//  CreateCallsListcallsInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CREATECALLSLISTCALLSINPUT
#define APIMATIC_CREATECALLSLISTCALLSINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol CreateCallsListcallsInput
@end

@interface CreateCallsListcallsInput : NSObject

/**
* The page count to retrieve from the total results in the collection. Page indexing starts at 1.
*/
@property int page;

/**
* Number of individual resources listed in the response per page
*/
@property int pageSize;

/**
* Filter calls that were sent to this 10-digit number (E.164 format).
*/
@property NSString* to;

/**
* Filter calls that were sent from this 10-digit number (E.164 format).
*/
@property NSString* from;

/**
* Return calls that are from a specified date.
*/
@property NSString* dateCreated;

@end
#endif