//
//  CreateConferencesDeafMuteParticipantInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CREATECONFERENCESDEAFMUTEPARTICIPANTINPUT
#define APIMATIC_CREATECONFERENCESDEAFMUTEPARTICIPANTINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol CreateConferencesDeafMuteParticipantInput
@end

@interface CreateConferencesDeafMuteParticipantInput : NSObject

/**
* ID of the active conference
*/
@property NSString* conferenceSid;

/**
* ID of an active participant
*/
@property NSString* participantSid;

/**
* Mute a participant
*/
@property NSNumber* muted;

/**
* Make it so a participant cant hear
*/
@property NSNumber* deaf;

@end
#endif