//
//  CreateUserSubaccountactivationInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateUserSubaccountactivationInput.h"

@implementation CreateUserSubaccountactivationInput

/**
* The SubaccountSid to be activated or suspended
*/
@synthesize subAccountSID;

/**
* 0 to suspend or 1 to activate
*/
@synthesize mActivate;

@end