//
//  CreateIncomingphoneListnumberInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CREATEINCOMINGPHONELISTNUMBERINPUT
#define APIMATIC_CREATEINCOMINGPHONELISTNUMBERINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "Numbertype16Enum.h"
#import "Numbertype16EnumHelper.h"


//protocol defined for deserialization of JSON
@protocol CreateIncomingphoneListnumberInput
@end

@interface CreateIncomingphoneListnumberInput : NSObject

/**
* Which page of the overall response will be returned. Page indexing starts at 1.
*/
@property int page;

/**
* The page count to retrieve from the total results in the collection. Page indexing starts at 1.
*/
@property int pageSize;

/**
* The capability supported by the number.Number type either SMS,Voice or all
*/
@property enum Numbertype16Enum numberType;

/**
* A human-readable label added to the number object.
*/
@property NSString* friendlyName;

@end
#endif