//
//  CreateConferencesAddParticipantInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateConferencesAddParticipantInput.h"

@implementation CreateConferencesAddParticipantInput

/**
* The unique identifier for a conference object.
*/
@synthesize conferenceSid;

/**
* The phone number of the participant to be added.
*/
@synthesize participantNumber;

/**
* Specifies if participant should be muted.
*/
@synthesize muted;

/**
* Specifies if the participant should hear audio in the conference.
*/
@synthesize deaf;

@end