//
//  CreateConferencesAddParticipantInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CREATECONFERENCESADDPARTICIPANTINPUT
#define APIMATIC_CREATECONFERENCESADDPARTICIPANTINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol CreateConferencesAddParticipantInput
@end

@interface CreateConferencesAddParticipantInput : NSObject

/**
* The unique identifier for a conference object.
*/
@property NSString* conferenceSid;

/**
* The phone number of the participant to be added.
*/
@property NSString* participantNumber;

/**
* Specifies if participant should be muted.
*/
@property NSNumber* muted;

/**
* Specifies if the participant should hear audio in the conference.
*/
@property NSNumber* deaf;

@end
#endif