//
//  CreateEmailListspamemailInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateEmailListspamemailInput.h"

@implementation CreateEmailListspamemailInput

/**
* The starting point of the list of spam emails that should be returned.
*/
@synthesize offset;

/**
* The count of results that should be returned.
*/
@synthesize limit;

@end