//
//  CreateIncomingphoneTransferphonenumbersInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateIncomingphoneTransferphonenumbersInput.h"

@implementation CreateIncomingphoneTransferphonenumbersInput

/**
* A valid 10-digit Ytel number (E.164 format).
*/
@synthesize phonenumber;

/**
* A specific Accountsid from where Number is getting transfer.
*/
@synthesize fromaccountsid;

/**
* A specific Accountsid to which Number is getting transfer.
*/
@synthesize toaccountsid;

@end