//
//  CreateCallsRecordcallsInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CREATECALLSRECORDCALLSINPUT
#define APIMATIC_CREATECALLSRECORDCALLSINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"

#import "DirectionEnum.h"
#import "DirectionEnumHelper.h"
#import "FileformatEnum.h"
#import "FileformatEnumHelper.h"


//protocol defined for deserialization of JSON
@protocol CreateCallsRecordcallsInput
@end

@interface CreateCallsRecordcallsInput : NSObject

/**
* The unique identifier of each call resource
*/
@property NSString* callSid;

/**
* Set true to initiate recording or false to terminate recording
*/
@property BOOL record;

/**
* The leg of the call to record
*/
@property enum DirectionEnum direction;

/**
* Time in seconds the recording duration should not exceed
*/
@property NSNumber* timeLimit;

/**
* URL consulted after the recording completes
*/
@property NSString* callBackUrl;

/**
* Format of the recording file. Can be .mp3 or .wav
*/
@property enum FileformatEnum fileformat;

@end
#endif