//
//  CreateUserDeletesubaccountInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateUserDeletesubaccountInput.h"

@implementation CreateUserDeletesubaccountInput

/**
* The SubaccountSid to be deleted
*/
@synthesize subAccountSID;

/**
* 0 to delete or 1 to merge numbers to parent account.
*/
@synthesize mergeNumber;

@end