//
//  CreateDedicatedshortcodeSendsmsInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_CREATEDEDICATEDSHORTCODESENDSMSINPUT
#define APIMATIC_CREATEDEDICATEDSHORTCODESENDSMSINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol CreateDedicatedshortcodeSendsmsInput
@end

@interface CreateDedicatedshortcodeSendsmsInput : NSObject

/**
* Your dedicated shortcode
*/
@property int shortcode;

/**
* The number to send your SMS to
*/
@property double to;

/**
* The body of your message
*/
@property NSString* body;

/**
* Specifies the HTTP method used to request the required URL once the Short Code message is sent.GET or POST
*/
@property NSString* method;

/**
* URL that can be requested to receive notification when Short Code message was sent.
*/
@property NSString* messagestatuscallback;

@end
#endif