//
//  CreateDedicatedshortcodeSendsmsInput.m
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import "CreateDedicatedshortcodeSendsmsInput.h"

@implementation CreateDedicatedshortcodeSendsmsInput

/**
* Your dedicated shortcode
*/
@synthesize shortcode;

/**
* The number to send your SMS to
*/
@synthesize to;

/**
* The body of your message
*/
@synthesize body;

/**
* Specifies the HTTP method used to request the required URL once the Short Code message is sent.GET or POST
*/
@synthesize method;

/**
* URL that can be requested to receive notification when Short Code message was sent.
*/
@synthesize messagestatuscallback;

@end