//
//  DirectionEnum.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_DIRECTIONENUM
#define APIMATIC_DIRECTIONENUM
 
enum DirectionEnum
{
        DirectionIN, //in direction
        DirectionOUT, //out direction
        DirectionBOTH, //both
};

#endif