//
//  FileformatEnum.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_FILEFORMATENUMHELPER
#define APIMATIC_FILEFORMATENUMHELPER

#include "FileformatEnum.h"

/**
* Helper class interface for FileformatEnum to NSString conversion
*/
@interface FileformatEnumHelper : NSObject

+(id) stringFromFileformatEnum:(enum FileformatEnum) fileformatEnum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromFileformatEnumArray:(NSArray<NSNumber*>*) array;


+(enum FileformatEnum) fileformatEnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) fileformatEnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif