//
//  FileformatEnum.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_FILEFORMATENUM
#define APIMATIC_FILEFORMATENUM
 
enum FileformatEnum
{
        FileformatMp3, //mp3 file
        FileformatWav, //wav file
};

#endif