//
//  GroupConfirmFileEnum.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_GROUPCONFIRMFILEENUM
#define APIMATIC_GROUPCONFIRMFILEENUM
 
enum GroupConfirmFileEnum
{
        GroupConfirmFileMp3, //mp3 file
        GroupConfirmFileWav, //wav file
};

#endif