//
//  GroupConfirmFileEnum.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#include "GroupConfirmFileEnumHelper.h"

/**
* Helper class implementation for GroupConfirmFileEnum to NSString conversion
*/
@implementation GroupConfirmFileEnumHelper

+(id) stringFromGroupConfirmFileEnum:(enum GroupConfirmFileEnum) groupConfirmFileEnum withDefault: (id) defaultValue
{
    switch(groupConfirmFileEnum)
    {
        case GroupConfirmFileMp3:
            return @"mp3";

        case GroupConfirmFileWav:
            return @"wav";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromGroupConfirmFileEnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [GroupConfirmFileEnumHelper stringFromGroupConfirmFileEnum:(enum GroupConfirmFileEnum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum GroupConfirmFileEnum) groupConfirmFileEnumFromString:(NSString*) strValue
{
    NSArray* GroupConfirmFileEnumArray = [NSArray arrayWithObjects:
                                        @"mp3",
                                        @"wav",
                                        nil];

    return (enum GroupConfirmFileEnum) [GroupConfirmFileEnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) groupConfirmFileEnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ GroupConfirmFileEnumHelper groupConfirmFileEnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end