//
//  HttpActionEnum.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_HTTPACTIONENUM
#define APIMATIC_HTTPACTIONENUM
 
enum HttpActionEnum
{
        HttpActionGET, //Get type
        HttpActionPOST, //Post Type
};

#endif