//
//  NumberTypeEnum.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_NUMBERTYPEENUM
#define APIMATIC_NUMBERTYPEENUM
 
enum NumberTypeEnum
{
        NumberTypeALL, //Get all phone Number type
        NumberTypeVoice, //Get only voice number type
        NumberTypeSMS, //Get Only SMs number type
};

#endif