//
//  Numbertype16Enum.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_NUMBERTYPE16ENUM
#define APIMATIC_NUMBERTYPE16ENUM
 
enum Numbertype16Enum
{
        Numbertype16ALL, //Get all phone Number type
        Numbertype16Voice, //Get only voice number type
        Numbertype16SMS, //Get Only SMs number type
};

#endif