//
//  PostcardListpostcardInput.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_POSTCARDLISTPOSTCARDINPUT
#define APIMATIC_POSTCARDLISTPOSTCARDINPUT

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"



//protocol defined for deserialization of JSON
@protocol PostcardListpostcardInput
@end

@interface PostcardListpostcardInput : NSObject

/**
* The page count to retrieve from the total results in the collection. Page indexing starts at 1.
*/
@property int page;

/**
* The count of objects to return per page.
*/
@property int pagesize;

/**
* The unique identifier for a postcard object.
*/
@property NSString* postcardid;

/**
* The date the postcard was created.
*/
@property NSString* dateCreated;

@end
#endif