//
//  ProductCodeEnum.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#ifndef APIMATIC_PRODUCTCODEENUM
#define APIMATIC_PRODUCTCODEENUM
typedef NS_ENUM(NSInteger, ProductCodeEnum)
{
        ProductCodeALL = 0, //TODO: Write general description for this method
        ProductCodeEnum1 = 1, //TODO: Write general description for this method
        ProductCodeEnum2 = 2, //TODO: Write general description for this method
        ProductCodeEnum3 = 3, //TODO: Write general description for this method
        ProductCodeEnum4 = 4, //TODO: Write general description for this method
        ProductCodeTranscription = 5, //TODO: Write general description for this method
        ProductCodeEmail = 6, //TODO: Write general description for this method
        ProductCodeConference = 7, //TODO: Write general description for this method
        ProductCodeCarrier = 8, //TODO: Write general description for this method
        ProductCodeEnum9 = 9, //TODO: Write general description for this method
        ProductCodeEnum10 = 10, //TODO: Write general description for this method
        ProductCodeEnum11 = 11, //TODO: Write general description for this method
        ProductCodeEnum12 = 12, //TODO: Write general description for this method
        ProductCodeEnum13 = 13, //TODO: Write general description for this method
};

#endif