//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <XCTest/XCTest.h>
#import "UsageController.h"
#import "TestHelper.h"
#import "TestBaseController.h"

@interface  TestUsageController : TestBaseController
//Controller instance for all tests
@property UsageController* controller;
@end 


@implementation  TestUsageController : TestBaseController

//Setup test class
//This method is called before the invocation of each test method in the test class
- (void)setUp {
    [super setUp];
    self.controller = [[UsageController alloc]init];
}

//Teardown test class
//This method is called after the invocation of each test method in the test class
- (void)tearDown {
    [super tearDown];
}	


// Retrieve usage metrics regarding your Ytel account. The results includes inbound/outbound voice calls and inbound/outbound SMS messages as well as carrier lookup requests.    
-(void) testTestListUsage {
    //Set up test expectations
    XCTestExpectation *expectation =[self expectationWithDescription:@"High Expectations"];
    // Parameters for the API call
    ProductCodeEnum productCode = nil;
    NSString* startDate = nil;
    NSString* endDate = nil;
    NSString* includeSubAccounts = nil;

    // Set callback and perform API call
    [self.controller createListUsageAsyncWithProductCode: productCode startDate : startDate endDate : endDate includeSubAccounts : includeSubAccounts  completionBlock:^(BOOL success, HttpContext* context, NSString* response, NSError* error) { 
       // Test response code
        XCTAssertEqual(200, context.response.statusCode);
        

        [expectation fulfill];
    }];
    [self wait];
}



@end
