//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <XCTest/XCTest.h>
#import "PhoneNumberController.h"
#import "TestHelper.h"
#import "TestBaseController.h"

@interface  TestPhoneNumberController : TestBaseController
//Controller instance for all tests
@property PhoneNumberController* controller;
@end 


@implementation  TestPhoneNumberController : TestBaseController

//Setup test class
//This method is called before the invocation of each test method in the test class
- (void)setUp {
    [super setUp];
    self.controller = [[PhoneNumberController alloc]init];
}

//Teardown test class
//This method is called after the invocation of each test method in the test class
- (void)tearDown {
    [super tearDown];
}	


// Retrieve a list of purchased phones numbers associated with your Ytel account.    
-(void) testTestListNumbers {
    //Set up test expectations
    XCTestExpectation *expectation =[self expectationWithDescription:@"High Expectations"];
    // Parameters for the API call
    NSNumber* page = nil;
    NSNumber* pageSize = nil;
    NumberType14Enum numberType = nil;
    NSString* friendlyName = nil;

    // Set callback and perform API call
    [self.controller createListNumbersAsyncWithPage: page pageSize : pageSize numberType : numberType friendlyName : friendlyName  completionBlock:^(BOOL success, HttpContext* context, NSString* response, NSError* error) { 
       // Test response code
        XCTAssertEqual(200, context.response.statusCode);
        

        [expectation fulfill];
    }];
    [self wait];
}



@end
