//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <XCTest/XCTest.h>
#import "ConferenceController.h"
#import "TestHelper.h"
#import "TestBaseController.h"

@interface  TestConferenceController : TestBaseController
//Controller instance for all tests
@property ConferenceController* controller;
@end 


@implementation  TestConferenceController : TestBaseController

//Setup test class
//This method is called before the invocation of each test method in the test class
- (void)setUp {
    [super setUp];
    self.controller = [[ConferenceController alloc]init];
}

//Teardown test class
//This method is called after the invocation of each test method in the test class
- (void)tearDown {
    [super tearDown];
}	


// Retrieve a list of conference objects.    
-(void) testTestListConferences {
    //Set up test expectations
    XCTestExpectation *expectation =[self expectationWithDescription:@"High Expectations"];
    // Parameters for the API call
    NSNumber* page = nil;
    NSNumber* pagesize = nil;
    NSString* friendlyName = nil;
    NSString* dateCreated = nil;

    // Set callback and perform API call
    [self.controller createListConferencesAsyncWithPage: page pagesize : pagesize friendlyName : friendlyName dateCreated : dateCreated  completionBlock:^(BOOL success, HttpContext* context, NSString* response, NSError* error) { 
       // Test response code
        XCTAssertEqual(200, context.response.statusCode);
        

        [expectation fulfill];
    }];
    [self wait];
}



@end
