//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <XCTest/XCTest.h>
#import "LetterController.h"
#import "TestHelper.h"
#import "TestBaseController.h"

@interface  TestLetterController : TestBaseController
//Controller instance for all tests
@property LetterController* controller;
@end 


@implementation  TestLetterController : TestBaseController

//Setup test class
//This method is called before the invocation of each test method in the test class
- (void)setUp {
    [super setUp];
    self.controller = [[LetterController alloc]init];
}

//Teardown test class
//This method is called after the invocation of each test method in the test class
- (void)tearDown {
    [super tearDown];
}	


// Retrieve a list of letter objects. The letter objects are sorted by creation date, with the most recently created letters appearing first.    
-(void) testTestListLetters {
    //Set up test expectations
    XCTestExpectation *expectation =[self expectationWithDescription:@"High Expectations"];
    // Parameters for the API call
    NSNumber* page = nil;
    NSNumber* pagesize = nil;
    NSString* lettersid = nil;
    NSString* dateCreated = nil;

    // Set callback and perform API call
    [self.controller createListLettersAsyncWithPage: page pagesize : pagesize lettersid : lettersid dateCreated : dateCreated  completionBlock:^(BOOL success, HttpContext* context, NSString* response, NSError* error) { 
       // Test response code
        XCTAssertEqual(200, context.response.statusCode);
        

        [expectation fulfill];
    }];
    [self wait];
}



@end
