//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <XCTest/XCTest.h>
#import "RecordingController.h"
#import "TestHelper.h"
#import "TestBaseController.h"

@interface  TestRecordingController : TestBaseController
//Controller instance for all tests
@property RecordingController* controller;
@end 


@implementation  TestRecordingController : TestBaseController

//Setup test class
//This method is called before the invocation of each test method in the test class
- (void)setUp {
    [super setUp];
    self.controller = [[RecordingController alloc]init];
}

//Teardown test class
//This method is called after the invocation of each test method in the test class
- (void)tearDown {
    [super tearDown];
}	


// Retrieve a list of recording objects.    
-(void) testTestListRecordings {
    //Set up test expectations
    XCTestExpectation *expectation =[self expectationWithDescription:@"High Expectations"];
    // Parameters for the API call
    NSNumber* page = nil;
    NSNumber* pagesize = nil;
    NSString* datecreated = nil;
    NSString* callsid = nil;

    // Set callback and perform API call
    [self.controller createListRecordingsAsyncWithPage: page pagesize : pagesize datecreated : datecreated callsid : callsid  completionBlock:^(BOOL success, HttpContext* context, NSString* response, NSError* error) { 
       // Test response code
        XCTAssertEqual(200, context.response.statusCode);
        

        [expectation fulfill];
    }];
    [self wait];
}



@end
