//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_AUDIOURLENUM
#define APIMATIC_AUDIOURLENUM
 
enum AudioUrlEnum
{
        AudioUrlMp3, //TODO: Write general description for this method
        AudioUrlWav, //TODO: Write general description for this method
};

#endif