//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_AUDIOURL43ENUMHELPER
#define APIMATIC_AUDIOURL43ENUMHELPER

#include "AudioUrl43Enum.h"

/**
* Helper class interface for AudioUrl43Enum to NSString conversion
*/
@interface AudioUrl43EnumHelper : NSObject

+(id) stringFromAudioUrl43Enum:(enum AudioUrl43Enum) audioUrl43Enum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromAudioUrl43EnumArray:(NSArray<NSNumber*>*) array;


+(enum AudioUrl43Enum) audioUrl43EnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) audioUrl43EnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif