//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_AUDIODIRECTION29ENUMHELPER
#define APIMATIC_AUDIODIRECTION29ENUMHELPER

#include "AudioDirection29Enum.h"

/**
* Helper class interface for AudioDirection29Enum to NSString conversion
*/
@interface AudioDirection29EnumHelper : NSObject

+(id) stringFromAudioDirection29Enum:(enum AudioDirection29Enum) audioDirection29Enum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromAudioDirection29EnumArray:(NSArray<NSNumber*>*) array;


+(enum AudioDirection29Enum) audioDirection29EnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) audioDirection29EnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif