//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_AUDIOURL43ENUM
#define APIMATIC_AUDIOURL43ENUM
 
enum AudioUrl43Enum
{
        AudioUrl43Mp3, //mp3 file
        AudioUrl43Wav, //wav file
};

#endif