//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_DIRECTION4ENUMHELPER
#define APIMATIC_DIRECTION4ENUMHELPER

#include "Direction4Enum.h"

/**
* Helper class interface for Direction4Enum to NSString conversion
*/
@interface Direction4EnumHelper : NSObject

+(id) stringFromDirection4Enum:(enum Direction4Enum) direction4Enum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromDirection4EnumArray:(NSArray<NSNumber*>*) array;


+(enum Direction4Enum) direction4EnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) direction4EnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif