//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_DIRECTIONENUM
#define APIMATIC_DIRECTIONENUM
 
enum DirectionEnum
{
        DirectionIn, //TODO: Write general description for this method
        DirectionOut, //TODO: Write general description for this method
        DirectionBoth, //TODO: Write general description for this method
};

#endif