//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_DIRECTION4ENUM
#define APIMATIC_DIRECTION4ENUM
 
enum Direction4Enum
{
        Direction4In, //TODO: Write general description for this method
        Direction4Out, //TODO: Write general description for this method
        Direction4Both, //TODO: Write general description for this method
};

#endif