//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#include "Direction23EnumHelper.h"

/**
* Helper class implementation for Direction23Enum to NSString conversion
*/
@implementation Direction23EnumHelper

+(id) stringFromDirection23Enum:(enum Direction23Enum) direction23Enum withDefault: (id) defaultValue
{
    switch(direction23Enum)
    {
        case Direction23IN:
            return @"in";

        case Direction23OUT:
            return @"out";

        case Direction23BOTH:
            return @"both";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromDirection23EnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [Direction23EnumHelper stringFromDirection23Enum:(enum Direction23Enum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum Direction23Enum) direction23EnumFromString:(NSString*) strValue
{
    NSArray* Direction23EnumArray = [NSArray arrayWithObjects:
                                        @"in",
                                        @"out",
                                        @"both",
                                        nil];

    return (enum Direction23Enum) [Direction23EnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) direction23EnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ Direction23EnumHelper direction23EnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end