//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_DIRECTION23ENUM
#define APIMATIC_DIRECTION23ENUM
 
enum Direction23Enum
{
        Direction23IN, //in direction
        Direction23OUT, //out direction
        Direction23BOTH, //both
};

#endif