//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_FILEFORMATENUM
#define APIMATIC_FILEFORMATENUM
 
enum FileformatEnum
{
        FileformatMp3, //TODO: Write general description for this method
        FileformatWav, //TODO: Write general description for this method
};

#endif