//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_FILEFORMAT37ENUM
#define APIMATIC_FILEFORMAT37ENUM
 
enum Fileformat37Enum
{
        Fileformat37Mp3, //mp3 file
        Fileformat37Wav, //wav file
};

#endif