//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_GROUPCONFIRMFILEENUM
#define APIMATIC_GROUPCONFIRMFILEENUM
 
enum GroupConfirmFileEnum
{
        GroupConfirmFileMp3, //TODO: Write general description for this method
        GroupConfirmFileWav, //TODO: Write general description for this method
};

#endif