//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_GROUPCONFIRMFILE44ENUM
#define APIMATIC_GROUPCONFIRMFILE44ENUM
 
enum GroupConfirmFile44Enum
{
        GroupConfirmFile44Mp3, //mp3 file
        GroupConfirmFile44Wav, //wav file
};

#endif