//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_GROUPCONFIRMFILE44ENUMHELPER
#define APIMATIC_GROUPCONFIRMFILE44ENUMHELPER

#include "GroupConfirmFile44Enum.h"

/**
* Helper class interface for GroupConfirmFile44Enum to NSString conversion
*/
@interface GroupConfirmFile44EnumHelper : NSObject

+(id) stringFromGroupConfirmFile44Enum:(enum GroupConfirmFile44Enum) groupConfirmFile44Enum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromGroupConfirmFile44EnumArray:(NSArray<NSNumber*>*) array;


+(enum GroupConfirmFile44Enum) groupConfirmFile44EnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) groupConfirmFile44EnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif