//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_IFMACHINEENUM
#define APIMATIC_IFMACHINEENUM
 
enum IfMachineEnum
{
        IfMachineContinue, //TODO: Write general description for this method
        IfMachineHangup, //TODO: Write general description for this method
};

#endif