//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#include "MergeNumber40EnumHelper.h"

/**
* Helper class implementation for MergeNumber40Enum to NSString conversion
*/
@implementation MergeNumber40EnumHelper

+(id) stringFromMergeNumber40Enum:(enum MergeNumber40Enum) mergeNumber40Enum withDefault: (id) defaultValue
{
    switch(mergeNumber40Enum)
    {
        case MergeNumber40Delete:
            return @"0";

        case MergeNumber40Merge:
            return @"1";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromMergeNumber40EnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [MergeNumber40EnumHelper stringFromMergeNumber40Enum:(enum MergeNumber40Enum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum MergeNumber40Enum) mergeNumber40EnumFromString:(NSString*) strValue
{
    NSArray* MergeNumber40EnumArray = [NSArray arrayWithObjects:
                                        @"0",
                                        @"1",
                                        nil];

    return (enum MergeNumber40Enum) [MergeNumber40EnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) mergeNumber40EnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ MergeNumber40EnumHelper mergeNumber40EnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end