//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_MERGENUMBERSTATUSENUM
#define APIMATIC_MERGENUMBERSTATUSENUM
typedef NS_ENUM(NSInteger, MergeNumberStatusEnum)
{
        MergeNumberStatusDelete = 0, //TODO: Write general description for this method
        MergeNumberStatusMerge = 1, //TODO: Write general description for this method
};

#endif