//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_MERGENUMBER40ENUM
#define APIMATIC_MERGENUMBER40ENUM
typedef NS_ENUM(NSInteger, MergeNumber40Enum)
{
        MergeNumber40Delete = 0, //TODO: Write general description for this method
        MergeNumber40Merge = 1, //TODO: Write general description for this method
};

#endif