//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#include "NumberType15EnumHelper.h"

/**
* Helper class implementation for NumberType15Enum to NSString conversion
*/
@implementation NumberType15EnumHelper

+(id) stringFromNumberType15Enum:(enum NumberType15Enum) numberType15Enum withDefault: (id) defaultValue
{
    switch(numberType15Enum)
    {
        case NumberType15All:
            return @"all";

        case NumberType15Voice:
            return @"voice";

        case NumberType15Sms:
            return @"sms";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromNumberType15EnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [NumberType15EnumHelper stringFromNumberType15Enum:(enum NumberType15Enum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum NumberType15Enum) numberType15EnumFromString:(NSString*) strValue
{
    NSArray* NumberType15EnumArray = [NSArray arrayWithObjects:
                                        @"all",
                                        @"voice",
                                        @"sms",
                                        nil];

    return (enum NumberType15Enum) [NumberType15EnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) numberType15EnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ NumberType15EnumHelper numberType15EnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end