//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_NUMBERTYPE24ENUMHELPER
#define APIMATIC_NUMBERTYPE24ENUMHELPER

#include "NumberType24Enum.h"

/**
* Helper class interface for NumberType24Enum to NSString conversion
*/
@interface NumberType24EnumHelper : NSObject

+(id) stringFromNumberType24Enum:(enum NumberType24Enum) numberType24Enum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromNumberType24EnumArray:(NSArray<NSNumber*>*) array;


+(enum NumberType24Enum) numberType24EnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) numberType24EnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif