//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_PLAYDTMFDIRECTION38ENUM
#define APIMATIC_PLAYDTMFDIRECTION38ENUM
 
enum PlayDtmfDirection38Enum
{
        PlayDtmfDirection38IN, //in direction
        PlayDtmfDirection38OUT, //out direction
        PlayDtmfDirection38BOTH, //both
};

#endif