//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#include "PlayDtmfDirectionEnumHelper.h"

/**
* Helper class implementation for PlayDtmfDirectionEnum to NSString conversion
*/
@implementation PlayDtmfDirectionEnumHelper

+(id) stringFromPlayDtmfDirectionEnum:(enum PlayDtmfDirectionEnum) playDtmfDirectionEnum withDefault: (id) defaultValue
{
    switch(playDtmfDirectionEnum)
    {
        case PlayDtmfDirectionIn:
            return @"in";

        case PlayDtmfDirectionOut:
            return @"out";

        case PlayDtmfDirectionBoth:
            return @"both";

        default:
            return defaultValue;
    }
}

+(NSArray<NSString*>*) stringArrayFromPlayDtmfDirectionEnumArray:(NSArray<NSNumber*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSNumber* numberValue in array){
        NSNumber* stringValue = [PlayDtmfDirectionEnumHelper stringFromPlayDtmfDirectionEnum:(enum PlayDtmfDirectionEnum) numberValue.intValue withDefault:[NSNull null]];
        [enums addObject:stringValue];
    }
    return [enums copy];
}

+(enum PlayDtmfDirectionEnum) playDtmfDirectionEnumFromString:(NSString*) strValue
{
    NSArray* PlayDtmfDirectionEnumArray = [NSArray arrayWithObjects:
                                        @"in",
                                        @"out",
                                        @"both",
                                        nil];

    return (enum PlayDtmfDirectionEnum) [PlayDtmfDirectionEnumArray indexOfObject: strValue];
}


+(NSArray<NSNumber*>*) playDtmfDirectionEnumArrayFromStringArray:(NSArray<NSString*>*) array
{
    NSMutableArray* enums = [[NSMutableArray alloc]init]; 
    for(NSString* enumValue in array){
        NSNumber* numberValue = [NSNumber numberWithInt:[ PlayDtmfDirectionEnumHelper playDtmfDirectionEnumFromString:enumValue]];
        [enums addObject:numberValue];
    }
    return [enums copy];
}

@end