//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_PRODUCTCODE30ENUM
#define APIMATIC_PRODUCTCODE30ENUM
typedef NS_ENUM(NSInteger, ProductCode30Enum)
{
        ProductCode30ALL = 0, //TODO: Write general description for this method
        ProductCode30Enum1 = 1, //TODO: Write general description for this method
        ProductCode30Enum2 = 2, //TODO: Write general description for this method
        ProductCode30Enum3 = 3, //TODO: Write general description for this method
        ProductCode30Enum4 = 4, //TODO: Write general description for this method
        ProductCode30Transcription = 5, //TODO: Write general description for this method
        ProductCode30Email = 6, //TODO: Write general description for this method
        ProductCode30Conference = 7, //TODO: Write general description for this method
        ProductCode30Carrier = 8, //TODO: Write general description for this method
        ProductCode30Enum9 = 9, //TODO: Write general description for this method
        ProductCode30Enum10 = 10, //TODO: Write general description for this method
        ProductCode30Enum11 = 11, //TODO: Write general description for this method
        ProductCode30Enum12 = 12, //TODO: Write general description for this method
        ProductCode30Enum13 = 13, //TODO: Write general description for this method
};

#endif