//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_PRODUCTCODE30ENUMHELPER
#define APIMATIC_PRODUCTCODE30ENUMHELPER

#include "ProductCode30Enum.h"

/**
* Helper class interface for ProductCode30Enum to NSString conversion
*/
@interface ProductCode30EnumHelper : NSObject

+(id) stringFromProductCode30Enum:(enum ProductCode30Enum) productCode30Enum withDefault: (id) defaultValue;

+(NSArray<NSString*>*) stringArrayFromProductCode30EnumArray:(NSArray<NSNumber*>*) array;


+(enum ProductCode30Enum) productCode30EnumFromString:(NSString*) strValue;

+(NSArray<NSNumber*>*) productCode30EnumArrayFromStringArray:(NSArray<NSString*>*) array;

@end

#endif