//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_PRODUCTCODE27ENUM
#define APIMATIC_PRODUCTCODE27ENUM
typedef NS_ENUM(NSInteger, ProductCode27Enum)
{
        ProductCode27ALL = 0, //TODO: Write general description for this method
        ProductCode27Enum1 = 1, //TODO: Write general description for this method
        ProductCode27Enum2 = 2, //TODO: Write general description for this method
        ProductCode27Enum3 = 3, //TODO: Write general description for this method
        ProductCode27Enum4 = 4, //TODO: Write general description for this method
        ProductCode27Transcription = 5, //TODO: Write general description for this method
        ProductCode27Email = 6, //TODO: Write general description for this method
        ProductCode27Conference = 7, //TODO: Write general description for this method
        ProductCode27Carrier = 8, //TODO: Write general description for this method
        ProductCode27Enum9 = 9, //TODO: Write general description for this method
        ProductCode27Enum10 = 10, //TODO: Write general description for this method
        ProductCode27Enum11 = 11, //TODO: Write general description for this method
        ProductCode27Enum12 = 12, //TODO: Write general description for this method
        ProductCode27Enum13 = 13, //TODO: Write general description for this method
};

#endif