//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_SENDEMAILASENUM
#define APIMATIC_SENDEMAILASENUM
 
enum SendEmailAsEnum
{
        SendEmailAsTEXT, //Email send as text format
        SendEmailAsHTML, //Email send as HTML format
};

#endif