//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_STATUS24ENUM
#define APIMATIC_STATUS24ENUM
 
enum Status24Enum
{
        Status24CANCELED, //Interrupt Call will be cancel
        Status24COMPLETED, //Interrupt Call is complete
};

#endif