//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_STATUS25ENUM
#define APIMATIC_STATUS25ENUM
 
enum Status25Enum
{
        Status25INPROGRESS, //TODO: Write general description for this method
        Status25Success, //TODO: Write general description for this method
        Status25Failure, //TODO: Write general description for this method
};

#endif