//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TYPE36ENUM
#define APIMATIC_TYPE36ENUM
 
enum Type36Enum
{
        Type36TEXT, //Email send as text format
        Type36HTML, //Email send as HTML format
};

#endif