//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef APIMATIC_TYPEENUM
#define APIMATIC_TYPEENUM
 
enum TypeEnum
{
        TypeText, //TODO: Write general description for this method
        TypeHtml, //TODO: Write general description for this method
};

#endif