//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#ifndef YtelAPIV3_Configuration_h
#define YtelAPIV3_Configuration_h

/** The base Uri for API calls */
extern NSString* Configuration_BaseUri;

/** The username to use with basic authentication */
/** extern reference to the config variable BasicAuthUserName */
extern NSString* Configuration_BasicAuthUserName;

/** The password to use with basic authentication */
/** extern reference to the config variable BasicAuthPassword */
extern NSString* Configuration_BasicAuthPassword;

#endif
