//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface AreaMailController : BaseController

/**
* Completion block definition for asynchronous call to Delete AreaMail */
typedef void (^CompletedPostDeleteAreaMail)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Remove an AreaMail object by its AreaMailId.
* @param    areamailid    Required parameter: The unique identifier for an AreaMail object.
*/
- (void) createDeleteAreaMailAsyncWithAreamailid:(NSString*) areamailid
                completionBlock:(CompletedPostDeleteAreaMail) onCompleted;

/**
* Completion block definition for asynchronous call to View AreaMail */
typedef void (^CompletedPostViewAreaMail)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Retrieve an AreaMail object by its AreaMailId.
* @param    areamailid    Required parameter: The unique identifier for an AreaMail object.
*/
- (void) createViewAreaMailAsyncWithAreamailid:(NSString*) areamailid
                completionBlock:(CompletedPostViewAreaMail) onCompleted;

/**
* Completion block definition for asynchronous call to List AreaMails */
typedef void (^CompletedPostListAreaMails)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Retrieve a list of AreaMail objects.
* @param    page    Optional parameter: The page count to retrieve from the total results in the collection. Page indexing starts at 1.
* @param    pagesize    Optional parameter: The count of objects to return per page.
* @param    areamailsid    Optional parameter: The unique identifier for an AreaMail object.
* @param    dateCreated    Optional parameter: The date the AreaMail was created.
*/
- (void) createListAreaMailsAsyncWithPage:(NSNumber*) page
                pagesize:(NSNumber*) pagesize
                areamailsid:(NSString*) areamailsid
                dateCreated:(NSString*) dateCreated
                completionBlock:(CompletedPostListAreaMails) onCompleted;

/**
* Completion block definition for asynchronous call to Create AreaMail */
typedef void (^CompletedPostCreateAreaMail)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Create a new AreaMail object.
* @param    routes    Required parameter: List of routes that AreaMail should be delivered to.  A single route can be either a zipcode or a carrier route.List of routes that AreaMail should be delivered to.  A single route can be either a zipcode or a carrier route. A carrier route is in the form of 92610-C043 where the carrier route is composed of 5 numbers for zipcode, 1 letter for carrier route type, and 3 numbers for carrier route code. Delivery can be sent to mutliple routes by separating them with a commas. Valid Values: 92656, 92610-C043
* @param    attachbyid    Required parameter: Set an existing areamail by attaching its AreamailId.
* @param    front    Required parameter: The front of the AreaMail item to be created. This can be a URL, local file, or an HTML string. Supported file types are PDF, PNG, and JPEG. Back required
* @param    back    Required parameter: The back of the AreaMail item to be created. This can be a URL, local file, or an HTML string. Supported file types are PDF, PNG, and JPEG.
* @param    description    Optional parameter: A string value to use as a description for this AreaMail item.
* @param    targettype    Optional parameter: The delivery location type.
* @param    htmldata    Optional parameter: A string value that contains HTML markup.
*/
- (void) createAreaMailAsyncWithRoutes:(NSString*) routes
                attachbyid:(NSString*) attachbyid
                front:(NSString*) front
                back:(NSString*) back
                description:(NSString*) description
                targettype:(NSString*) targettype
                htmldata:(NSString*) htmldata
                completionBlock:(CompletedPostCreateAreaMail) onCompleted;

@end