//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface CarrierController : BaseController

/**
* Completion block definition for asynchronous call to Lookup Carrier */
typedef void (^CompletedPostLookupCarrier)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Get the Carrier Lookup
* @param    phoneNumber    Required parameter: A valid 10-digit number (E.164 format).
*/
- (void) createLookupCarrierAsyncWithPhoneNumber:(NSString*) phoneNumber
                completionBlock:(CompletedPostLookupCarrier) onCompleted;

/**
* Completion block definition for asynchronous call to Carrier Results */
typedef void (^CompletedPostCarrierResults)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Retrieve a list of carrier lookup objects.
* @param    page    Optional parameter: The page count to retrieve from the total results in the collection. Page indexing starts at 1.
* @param    pageSize    Optional parameter: The count of objects to return per page.
*/
- (void) createCarrierResultsAsyncWithPage:(NSNumber*) page
                pageSize:(NSNumber*) pageSize
                completionBlock:(CompletedPostCarrierResults) onCompleted;

@end