//
//  YtelAPIV3
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "ProductCodeEnum.h"
#import "ProductCodeEnumHelper.h"

@interface UsageController : BaseController

/**
* Completion block definition for asynchronous call to List Usage */
typedef void (^CompletedPostListUsage)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Retrieve usage metrics regarding your Ytel account. The results includes inbound/outbound voice calls and inbound/outbound SMS messages as well as carrier lookup requests.
* @param    productCode    Optional parameter: Filter usage results by product type.
* @param    startDate    Optional parameter: Filter usage objects by start date.
* @param    endDate    Optional parameter: Filter usage objects by end date.
* @param    includeSubAccounts    Optional parameter: Will include all subaccount usage data
*/
- (void) createListUsageAsyncWithProductCode:(enum ProductCodeEnum) productCode
                startDate:(NSString*) startDate
                endDate:(NSString*) endDate
                includeSubAccounts:(NSString*) includeSubAccounts
                completionBlock:(CompletedPostListUsage) onCompleted;

@end