//
//  AccountController.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"

@interface AccountController : BaseController

/**
* Completion block definition for asynchronous call to AccountsViewaccount */
typedef void (^CompletedPostAccountsViewaccount)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Retrieve information regarding your Ytel account by a specific date. The response object will contain data such as account status, balance, and account usage totals.
* @param    date    Required parameter: Filter account information based on date.
*/
- (void) createAccountsViewaccountAsyncWithDate:(NSString*) date
                completionBlock:(CompletedPostAccountsViewaccount) onCompleted;

@end