//
//  AreaMailController.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "CreateAreamailCreateInput.h"
#import "CreateAreamailListsInput.h"

@interface AreaMailController : BaseController

/**
* Completion block definition for asynchronous call to AreamailDelete */
typedef void (^CompletedPostAreamailDelete)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Remove an AreaMail object by its AreaMailId.
* @param    areamailid    Required parameter: The unique identifier for an AreaMail object.
*/
- (void) createAreamailDeleteAsyncWithAreamailid:(NSString*) areamailid
                completionBlock:(CompletedPostAreamailDelete) onCompleted;

/**
* Completion block definition for asynchronous call to AreamailCreate */
typedef void (^CompletedPostAreamailCreate)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Create a new AreaMail object.
* @param  CreateAreamailCreateInput     Object with all parameters
*/
- (void) createAreamailCreateAsyncWithCreateAreamailCreateInput:(CreateAreamailCreateInput*) input
                completionBlock:(CompletedPostAreamailCreate) onCompleted;

/**
* Completion block definition for asynchronous call to AreamailView */
typedef void (^CompletedPostAreamailView)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Retrieve an AreaMail object by its AreaMailId.
* @param    areamailid    Required parameter: The unique identifier for an AreaMail object.
*/
- (void) createAreamailViewAsyncWithAreamailid:(NSString*) areamailid
                completionBlock:(CompletedPostAreamailView) onCompleted;

/**
* Completion block definition for asynchronous call to AreamailLists */
typedef void (^CompletedPostAreamailLists)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Retrieve a list of AreaMail objects.
* @param  CreateAreamailListsInput     Object with all parameters
*/
- (void) createAreamailListsAsyncWithCreateAreamailListsInput:(CreateAreamailListsInput*) input
                completionBlock:(CompletedPostAreamailLists) onCompleted;

@end