//
//  SMSController.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "CreateSmsGetinboundsmsInput.h"
#import "CreateSmsListsmsInput.h"
#import "CreateSmsSendsmsInput.h"

@interface SMSController : BaseController

/**
* Completion block definition for asynchronous call to SmsViewdetailsms */
typedef void (^CompletedPostSmsViewdetailsms)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Retrieve a single SMS message object with details by its SmsSid.
* @param    messageSid    Required parameter: The unique identifier for a sms message.
*/
- (void) createSmsViewdetailsmsAsyncWithMessageSid:(NSString*) messageSid
                completionBlock:(CompletedPostSmsViewdetailsms) onCompleted;

/**
* Completion block definition for asynchronous call to SmsViewsms */
typedef void (^CompletedPostSmsViewsms)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Retrieve a single SMS message object by its SmsSid.
* @param    messageSid    Required parameter: The unique identifier for a sms message.
*/
- (void) createSmsViewsmsAsyncWithMessageSid:(NSString*) messageSid
                completionBlock:(CompletedPostSmsViewsms) onCompleted;

/**
* Completion block definition for asynchronous call to SmsGetinboundsms */
typedef void (^CompletedPostSmsGetinboundsms)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Retrieve a list of Inbound SMS message objects.
* @param  CreateSmsGetinboundsmsInput     Object with all parameters
*/
- (void) createSmsGetinboundsmsAsyncWithCreateSmsGetinboundsmsInput:(CreateSmsGetinboundsmsInput*) input
                completionBlock:(CompletedPostSmsGetinboundsms) onCompleted;

/**
* Completion block definition for asynchronous call to SmsListsms */
typedef void (^CompletedPostSmsListsms)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Retrieve a list of Outbound SMS message objects.
* @param  CreateSmsListsmsInput     Object with all parameters
*/
- (void) createSmsListsmsAsyncWithCreateSmsListsmsInput:(CreateSmsListsmsInput*) input
                completionBlock:(CompletedPostSmsListsms) onCompleted;

/**
* Completion block definition for asynchronous call to SmsSendsms */
typedef void (^CompletedPostSmsSendsms)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Send an SMS from a Ytel number
* @param  CreateSmsSendsmsInput     Object with all parameters
*/
- (void) createSmsSendsmsAsyncWithCreateSmsSendsmsInput:(CreateSmsSendsmsInput*) input
                completionBlock:(CompletedPostSmsSendsms) onCompleted;

@end