//
//  SubAccountController.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "MActivateEnum.h"
#import "MActivateEnumHelper.h"
#import "CreateUserSubaccountactivationInput.h"
#import "MergeNumberEnum.h"
#import "MergeNumberEnumHelper.h"
#import "CreateUserDeletesubaccountInput.h"
#import "CreateUserCreatesubaccountInput.h"

@interface SubAccountController : BaseController

/**
* Completion block definition for asynchronous call to UserSubaccountactivation */
typedef void (^CompletedPostUserSubaccountactivation)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Suspend or unsuspend
* @param  CreateUserSubaccountactivationInput     Object with all parameters
*/
- (void) createUserSubaccountactivationAsyncWithCreateUserSubaccountactivationInput:(CreateUserSubaccountactivationInput*) input
                completionBlock:(CompletedPostUserSubaccountactivation) onCompleted;

/**
* Completion block definition for asynchronous call to UserDeletesubaccount */
typedef void (^CompletedPostUserDeletesubaccount)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Delete sub account or merge numbers into parent
* @param  CreateUserDeletesubaccountInput     Object with all parameters
*/
- (void) createUserDeletesubaccountAsyncWithCreateUserDeletesubaccountInput:(CreateUserDeletesubaccountInput*) input
                completionBlock:(CompletedPostUserDeletesubaccount) onCompleted;

/**
* Completion block definition for asynchronous call to UserCreatesubaccount */
typedef void (^CompletedPostUserCreatesubaccount)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Create a sub user account under the parent account
* @param  CreateUserCreatesubaccountInput     Object with all parameters
*/
- (void) createUserCreatesubaccountAsyncWithCreateUserCreatesubaccountInput:(CreateUserCreatesubaccountInput*) input
                completionBlock:(CompletedPostUserCreatesubaccount) onCompleted;

@end