//
//  UsageController.h
//  YtelAPI
//
//  This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
//
#import <Foundation/Foundation.h>
#import "Configuration.h"
#import "APIHelper.h"
#import "APIError.h"
#import "BaseController.h"
#import "UnirestClient.h"
#import "HttpContext.h"
#import "ProductCode27Enum.h"
#import "ProductCode27EnumHelper.h"
#import "CreateUsageListusageInput.h"

@interface UsageController : BaseController

/**
* Completion block definition for asynchronous call to UsageListusage */
typedef void (^CompletedPostUsageListusage)(BOOL success, HttpContext* context, NSString* response, NSError* error);

/**
* Retrieve usage metrics regarding your Ytel account. The results includes inbound/outbound voice calls and inbound/outbound SMS messages as well as carrier lookup requests.
* @param  CreateUsageListusageInput     Object with all parameters
*/
- (void) createUsageListusageAsyncWithCreateUsageListusageInput:(CreateUsageListusageInput*) input
                completionBlock:(CompletedPostUsageListusage) onCompleted;

@end